### ISSUE TITLE
Konfiguracja metod dostawy

### ISSUE THREAD

**Issue by Pablo1618** [Pablo1618/Geekup-Prestashop#8]
Należy zdefiniować dwóch nowych przewoźników. Należy dostosować 
ustawienia przewoźników, tak aby dla zamówień powyżej 2000 zł dostawa 
powinna być darmowa. Dla produktów cięższych niż 50 kg dostawa powinna 
być niemożliwa. Opłaty dla przewoźników powinny być różne.

**Comment by DomiDomi03** [comment]
Dodani są 3 nowi przewoźnicy, plus została dostawa do sklepu stacjonarnego (tam jest wyjątkowo darmowa dostawa), reszta ma darmową dostawę od 2000 zł i żaden towar nie może przekroczyć 50kg.
